### ISSUE TITLE
False Positive with Compat Layer type mods.

### ISSUE THREAD

**Issue by SkyanUltra** [DevilGlitch/Minecraft-Mod-Compatibility-Checker#1]
Some mods that are meant to act as a bridge for mods compatible for other mods such as Curios and Curios Compat Layer for Accessories bring up a false positive. These mods work fine when launched together, as they're meant to allow mods using the Curios API to be compatible with Accessories' API.

[conflicting_jars.txt](https://github.com/user-attachments/files/17531892/conflicting_jars.txt)

**Comment by DevilGlitch** [comment]
"ezMMCC is prone to hit false positives if you get exit code 1 while launching minecraft this is a great tool to figure out which mods are acting up."

**Comment by DevilGlitch** [comment]
Im working on adding a log reader function in the future @SkyanUltra but it will give false positives on some occasions bc of the way it works. Stay tuned for an update or read the logs

**Comment by DevilGlitch** [comment]
If you are still having issues feel free to drop your crash log and ill tell you what mod is fucking up. if not ill close the ticket

**Comment by SkyanUltra** [comment]
no, i'm not having anymore issues. thanks for the help though
